### ISSUE TITLE
The Japanese subtitle json file is left blank.

### ISSUE THREAD

**Issue by ohlordIwantto** [BrianWill/japanese_vocab#10]
I tried to import a story, but the Japanese subtitle won't upload even though the English one will. I don't have Go installed (on Windows) if that's any indication. 

[Wistoria： Wand and Sword - Episode 01 [English Sub] [uAS2RXlPsAk].en.json](https://github.com/user-attachments/files/17179704/Wistoria.Wand.and.Sword.-.Episode.01.English.Sub.uAS2RXlPsAk.en.json)
[Wistoria： Wand and Sword - Episode 01 [English Sub] [uAS2RXlPsAk].ja.json](https://github.com/user-attachments/files/17179701/Wistoria.Wand.and.Sword.-.Episode.01.English.Sub.uAS2RXlPsAk.ja.json)

EDIT:
I was sleepy while writing this. I meant that the Japanese subtitle file (VTT) was fine, but the .json file created did not have anything (Just a []). The count imported number also did not go up. This only happens to the Japanese one and not the English, so is there anything I might not have installed on my computer that I need?

**Comment by BrianWill** [comment]
Hmm, are you sure the subtitle file had the correct name? In this case, it would be ` Wistoria： Wand and Sword - Episode 01 [English Sub] [uAS2RXlPsAk].ja.vtt`.

I've just made quite a lot of changes, so you may want to check out the latest release. (Note that the 'sources' directory is now under the root, not under 'static').

**Comment by ohlordIwantto** [comment]
Ah, it works now. Thanks!
