### ISSUE TITLE
Build instructions can produce non-working binary for linux

### ISSUE THREAD

**Issue by joeholley** [BrianWill/japanese_vocab#8]
Tested on WSL Ubuntu version 2204.2.33.0, but this might happen on any OS if golang can't find the c compiler. Build instructions in the readme don't throw up an error, but since this environment doesn't come with gcc installed, the binary produced won't run:

```
$ go build
$ ./japanese
2023/10/10 19:56:56 Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

Resolved by installing gcc (for ubuntu: ``, which sets the golang compiler to enable CGO):
```
$ sudo apt install -y build-essential
(output elided)
$ go build
$ ./japanese
time to load kanji:  141.37979ms
time to unzip entries:  714.373175ms
time to load entries:  656.787842ms
time to build entry maps:  157.713199ms
2023/10/10 19:58:25 Defaulting to port 8080
2023/10/10 19:58:25 Running on port: 8080
```

Awesome app, BTW. Maybe just mention in the readme that one of the imported modules requires CGO?

**Comment by BrianWill** [comment]
Thanks, I made a note of this in the install instructions
